name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    runs-on: macos-latest

    env:
      RUSTFLAGS: --deny warnings

    steps:
      - uses: actions/checkout@v4

      - name: Download actionlint
        id: actionlint
        run:
          bash <(curl
          https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow
        run: ${{ steps.actionlint.outputs.executable }} -color

      - name: Install rust toolchain components
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Install client dependencies
        run: npm ci

      - name: Install mongodb
        run: |
          brew tap mongodb/brew
          brew install mongodb-community@6.0
          brew services start mongodb-community@6.0

      - name: Info
        run: |
          rustup --version
          cargo --version
          cargo clippy --version

      - name: Forbid
        run: |
          brew install ripgrep
          ./bin/forbid

      - name: Build
        run: cargo build --workspace --all-features --all-targets

      - name: Clippy
        run: ./bin/clippy

      - name: Check lockfile
        run: cargo update --locked --package stream

      - name: Check rust formatting
        run: cargo fmt --all -- --check

      - name: Lint typescript code
        run: npm run lint

      - name: Check typescript formatting
        run: npm run format-check

      - name: Test
        run: cargo test --workspace --all-features --all-targets
